// utils/desc.js
import { MaterialCommunityIcons } from '@expo/vector-icons';

export const desc = [
  { id: 200, text: "가벼운 비를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { id: 201, text: "비를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { id: 202, text: "폭우를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { id: 210, text: "약한 천둥구름", icon: "weather-lightning" },
  { id: 211, text: "천둥구름", icon: "weather-lightning" },
  { id: 212, text: "강한 천둥구름", icon: "weather-lightning" },
  { id: 221, text: "불규칙적 천둥구름", icon: "weather-lightning" },
  { id: 230, text: "약한 연무를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { id: 231, text: "연무를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { id: 232, text: "강한 안개비를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { id: 300, text: "가벼운 안개비", icon: "weather-partly-rainy" },
  { id: 301, text: "안개비", icon: "weather-partly-rainy" },
  { id: 302, text: "강한 안개비", icon: "weather-rainy" },
  { id: 310, text: "가벼운 적은비", icon: "weather-partly-rainy" },
  { id: 311, text: "적은비", icon: "weather-partly-rainy" },
  { id: 312, text: "강한 적은비", icon: "weather-rainy" },
  { id: 313, text: "소나기와 안개비", icon: "weather-pouring" },
  { id: 314, text: "강한 소나기와 안개비", icon: "weather-pouring" },
  { id: 321, text: "소나기", icon: "weather-pouring" },
  { id: 500, text: "약한 비", icon: "weather-rainy" },
  { id: 501, text: "중간 비", icon: "weather-rainy" },
  { id: 502, text: "강한 비", icon: "weather-pouring" },
  { id: 503, text: "매우 강한 비", icon: "weather-pouring" },
  { id: 504, text: "극심한 비", icon: "weather-pouring" },
  { id: 511, text: "우박", icon: "weather-hail" },
  { id: 520, text: "약한 소나기 비", icon: "weather-rainy" },
  { id: 521, text: "소나기 비", icon: "weather-rainy" },
  { id: 522, text: "강한 소나기 비", icon: "weather-pouring" },
  { id: 531, text: "불규칙적 소나기 비", icon: "weather-pouring" },
  { id: 600, text: "가벼운 눈", icon: "weather-snowy" },
  { id: 601, text: "눈", icon: "weather-snowy" },
  { id: 602, text: "강한 눈", icon: "weather-snowy-heavy" },
  { id: 611, text: "진눈깨비", icon: "weather-snowy-rainy" },
  { id: 612, text: "소나기 진눈깨비", icon: "weather-snowy-rainy" },
  { id: 615, text: "약한 비와 눈", icon: "weather-snowy-rainy" },
  { id: 616, text: "비와 눈", icon: "weather-snowy-rainy" },
  { id: 620, text: "약한 소나기 눈", icon: "weather-snowy" },
  { id: 621, text: "소나기 눈", icon: "weather-snowy" },
  { id: 622, text: "강한 소나기 눈", icon: "weather-snowy-heavy" },
  { id: 701, text: "박무", icon: "weather-fog" },
  { id: 711, text: "연기", icon: "weather-fog" },
  { id: 721, text: "연무", icon: "weather-fog" },
  { id: 731, text: "모래 먼지", icon: "weather-windy" },
  { id: 741, text: "안개", icon: "weather-fog" },
  { id: 751, text: "모래", icon: "weather-windy" },
  { id: 761, text: "먼지", icon: "weather-windy" },
  { id: 762, text: "화산재", icon: "weather-cloudy-alert" },
  { id: 771, text: "돌풍", icon: "weather-windy" },
  { id: 781, text: "토네이도", icon: "weather-tornado" },
  { id: 800, text: "구름 한 점 없는 맑은 하늘", icon: "weather-sunny" },
  { id: 801, text: "약간의 구름이 낀 하늘", icon: "weather-partly-cloudy" },
  { id: 802, text: "드문드문 구름이 낀 하늘", icon: "weather-partly-cloudy" },
  { id: 803, text: "구름이 거의 없는 하늘", icon: "weather-cloudy" },
  { id: 804, text: "구름으로 뒤덮인 흐린 하늘", icon: "weather-cloudy" },
  { id: 900, text: "토네이도", icon: "weather-tornado" },
  { id: 901, text: "태풍", icon: "weather-hurricane" },
  { id: 902, text: "허리케인", icon: "weather-hurricane" },
  { id: 903, text: "한랭", icon: "snowflake" },
  { id: 904, text: "고온", icon: "weather-sunny-alert" },
  { id: 905, text: "바람부는", icon: "weather-windy" },
  { id: 906, text: "우박", icon: "weather-hail" },
  { id: 951, text: "바람이 거의 없는", icon: "weather-windy" },
  { id: 952, text: "약한 바람", icon: "weather-windy" },
  { id: 953, text: "부드러운 바람", icon: "weather-windy" },
  { id: 954, text: "중간 세기 바람", icon: "weather-windy" },
  { id: 955, text: "신선한 바람", icon: "weather-windy" },
  { id: 956, text: "센 바람", icon: "weather-windy" },
  { id: 957, text: "돌풍에 가까운 센 바람", icon: "weather-windy" },
  { id: 958, text: "돌풍", icon: "weather-windy" },
  { id: 959, text: "심각한 돌풍", icon: "weather-windy" },
  { id: 960, text: "폭풍", icon: "weather-hurricane" },
  { id: 961, text: "강한 폭풍", icon: "weather-hurricane" },
  { id: 962, text: "허리케인", icon: "weather-hurricane" }
];
